default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tw_sample_development

test:
  <<: *default
  database: tw_sample_test

production:
  <<: *default
  database: tw_sample_production
  username: tw_sample
  password: <%= ENV['TW_SAMPLE_DATABASE_PASSWORD'] %>
